module.exports = {
  products: [
    {
      _id:'1',
      name:'Full Zip Running Shirts',
      category:'Shirts',
      image:'/images/product-1.jpg',
      price:60,
      brand:'Hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInstock: 6,
    },
    {
      _id:'2',
      name:'Full Zip Running Shirts',
      category:'Shirts',
      image:'/images/product-2.jpg',
      price:70,
      brand:'Hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInstock: 6,
    },
    {
      _id:'3',
      name:'Full Zip Running Shirts',
      category:'Shirts',
      image:'/images/product-3.jpg',
      price:59,
      brand:'Hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInstock: 6,
    },
    {
      _id:'4',
      name:'Full Zip Running Shirts',
      category:'Shirts',
      image:'/images/product-4.jpg',
      price:60,
      brand:'Hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInstock: 6,
    },
    {
      _id:'5',
      name:'Full Zip Running Shirts',
      category:'Shirts',
      image:'/images/product-5.jpg',
      price:78,
      brand:'Hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInstock: 6,
    },
    {
      _id:'6',
      name:'Full Zip Running Shirts',
      category:'Shirts',
      image:'/images/product-6.jpg',
      price:80,
      brand:'Hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInstock: 6,
    },
  ],
}